version: '3.7'

services: 
  postgres:
    container_name: DB_postgres_12
    image: "postgres:12"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/data/postgres"
    volumes: 
      - postgres_vol:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    network_mode: bridge

volumes: 
  postgres_vol:
