version: '3.7'

services: 
  postgres:
    container_name: postgres_container
    hostname: postgres_host
    image: "postgres:12"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/data/postgres"
    volumes: 
      - postgres_vol:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    # network_mode: bridge
    networks:
      - container_net

volumes: 
  postgres_vol:

networks:
  container_net:
    name: container_net
    driver: bridge
