version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672 # TCP6 - PUERTO PRINCIPAL DE RABBITMQ 
      - 15672:15672 # CONSOLA DE GESTION DE RABBITMQ V 3.X.X 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    restart: always
    network_mode: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:

# User: guest
# Password: guest
