version: '3.7'

services:
  rabbitmq:
    # image: rabbitmq:3-management-alpine
    build: # 
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 1883:1883 # PORT MQTT
      - 5672:5672 # TCP6 - PUERTO PRINCIPAL DE RABBITMQ 
      - 15672:15672 # CONSOLA DE GESTION DE RABBITMQ V 3.X.X 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    restart: always
    network_mode: bridge
    networks:
      - container_net

volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  container_net:

# User: guest
# Password: guest
