version: '3.8'

services: 
  mongo:
    image: 'mongo'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    volumes:
      - mongo_vol:/data/db
    ports:
      - 27017:27017
    restart: always
    network_mode: bridge

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo:mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'root'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'root'
    restart: always
    network_mode: bridge

volumes: 
  mongo_vol:
