version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    network_mode: bridge
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - mysql_vol:/var/lib/mysql
# Names our volume
volumes:
  mysql_vol:

# How to use dbever error conecction is with driver, you solution is https://ganeshchandrasekaran.com/dbeaver-public-key-retrieval-is-not-allowed-77eba055bbcd