version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    volumes:
      - events_mssql:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw@rd
      - MSSQL_PID=Developer
      # - MSSQL_DB=events_service
      # - MSSQL_USER=admin
      # - MSSQL_PASSWORD=Passw@rd
      # - MSSQL_DB_AUDIT_LOG=events_service_audit_log
    networks:
      - container_net
volumes:
  events_mssql:

networks:
  container_net: