# docker-compose.yml
version: '3'
services:
  redis:
    container_name: redis 
    image: redis:5.0.10-alpine # use latest official postgres version
    restart: always
    volumes:
      - redis_vol:/data # persist data even if container shuts down
    ports: 
      - 6379:6379
    networks:
      - dev_net

volumes:
  redis_vol:

networks:
  dev_net:
    external:
      name: dev_network