version: '3.7'

services:
  redis:
    image: redis:6-alpine
    volumes:
      - redis_vol:/data
    ports: 
      - 6379:6379
    restart: always
    network_mode: bridge
    networks:
      - container_net
volumes:
  redis_vol:

networks:
  container_net: